/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cbsproje;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Anıl
 */
public class Pencere extends javax.swing.JFrame {

    private int kucukNoktaX = 10, kucukNoktaY = 10;
    private int ortaNoktaX = 20, ortaNoktaY = 20;
    private int buyukNoktaX = 30, buyukNoktaY = 30;
    private int cizimAlaniX;
    private int cizimAlaniy;
    private int poligonNoktaSayisi;
    private ArrayList<Integer> xK = new ArrayList<>();
    private ArrayList<Integer> yK = new ArrayList<>();
    Graphics2D sekil;

    @Override
    public void paint(Graphics g) {
        super.paint(g); //To change body of generated methods, choose Tools | Templates.
    }

    public Pencere() {

        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        setVisible(true);

    }

    public int getPoligonNoktaSayisi() {
        return poligonNoktaSayisi;
    }

    public void setPoligonNoktaSayisi(int poligonNoktaSayisi) {
        this.poligonNoktaSayisi = poligonNoktaSayisi;
    }

    public int getKucukNoktaX() {
        return kucukNoktaX;
    }

    public int getOrtaNoktaX() {
        return ortaNoktaX;
    }

    public int getBuyukNoktaX() {
        return buyukNoktaX;
    }

    public int getKucukNoktaY() {
        return kucukNoktaY;
    }

    public int getOrtaNoktaY() {
        return ortaNoktaY;
    }

    public int getBuyukNoktaY() {
        return buyukNoktaY;
    }

    public int getCizimAlaniX() {
        return cizimAlaniX;
    }

    public void setCizimAlaniX(int cizimAlaniX) {
        this.cizimAlaniX = cizimAlaniX;
    }

    public int getCizimAlaniy() {
        return cizimAlaniy;
    }

    public void setCizimAlaniy(int cizimAlaniy) {
        this.cizimAlaniy = cizimAlaniy;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noktaGrup = new javax.swing.ButtonGroup();
        cizgiGrup = new javax.swing.ButtonGroup();
        poligonGrup = new javax.swing.ButtonGroup();
        secenekGrup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        labelNokta = new javax.swing.JLabel();
        labelCizgi = new javax.swing.JLabel();
        labelPoligon = new javax.swing.JLabel();
        nokta = new javax.swing.JRadioButton();
        cizgi = new javax.swing.JRadioButton();
        poligon = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        k_noktaSec = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        o_noktaSec = new javax.swing.JRadioButton();
        b_noktaSec = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        i_cizgiSec = new javax.swing.JRadioButton();
        o_cizgiSec = new javax.swing.JRadioButton();
        k_cizgiSec = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        p_bosSec = new javax.swing.JRadioButton();
        p_doluSec = new javax.swing.JRadioButton();
        p_taraliSec = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        xBoyutu = new javax.swing.JTextField();
        yBoyutu = new javax.swing.JTextField();
        olusturButon = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        xKoordinat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        yKoordinat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ekle1 = new javax.swing.JButton();
        ekle2 = new javax.swing.JButton();
        temizle = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(16, 10, 64));

        jPanel2.setBackground(new java.awt.Color(135, 250, 248));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Seçenek"));
        jPanel2.setForeground(new java.awt.Color(35, 8, 141));

        labelNokta.setText("Nokta:");

        labelCizgi.setText("Çizgi:");

        labelPoligon.setText("Poligon:");

        secenekGrup.add(nokta);
        nokta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nokta.setText("Seç");
        nokta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noktaActionPerformed(evt);
            }
        });

        secenekGrup.add(cizgi);
        cizgi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cizgi.setText("Seç");
        cizgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cizgiActionPerformed(evt);
            }
        });

        secenekGrup.add(poligon);
        poligon.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        poligon.setText("Seç");
        poligon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poligonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNokta)
                            .addComponent(labelCizgi))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nokta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cizgi)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelPoligon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(poligon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNokta)
                    .addComponent(nokta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cizgi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCizgi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPoligon)
                    .addComponent(poligon, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel3.setBackground(new java.awt.Color(135, 250, 248));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ayar"));
        jPanel3.setForeground(new java.awt.Color(35, 8, 141));

        jLabel4.setText("Nokta");

        noktaGrup.add(k_noktaSec);
        k_noktaSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        k_noktaSec.setSelected(true);
        k_noktaSec.setText("Küçük");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        noktaGrup.add(o_noktaSec);
        o_noktaSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        o_noktaSec.setText("Orta");

        noktaGrup.add(b_noktaSec);
        b_noktaSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        b_noktaSec.setText("Büyük");

        jLabel1.setText("Çizgi");

        cizgiGrup.add(i_cizgiSec);
        i_cizgiSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        i_cizgiSec.setSelected(true);
        i_cizgiSec.setText("İnce");

        cizgiGrup.add(o_cizgiSec);
        o_cizgiSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        o_cizgiSec.setText("Orta");
        o_cizgiSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                o_cizgiSecActionPerformed(evt);
            }
        });

        cizgiGrup.add(k_cizgiSec);
        k_cizgiSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        k_cizgiSec.setText("Kalın");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("Poligon");

        poligonGrup.add(p_bosSec);
        p_bosSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        p_bosSec.setSelected(true);
        p_bosSec.setText("İçi Boş");

        poligonGrup.add(p_doluSec);
        p_doluSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        p_doluSec.setText("İçi Dolu");

        poligonGrup.add(p_taraliSec);
        p_taraliSec.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        p_taraliSec.setText("İçi Taralı");
        p_taraliSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_taraliSecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(k_noktaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(o_noktaSec)
                    .addComponent(b_noktaSec)
                    .addComponent(jLabel4))
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(o_cizgiSec)
                    .addComponent(i_cizgiSec, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(k_cizgiSec)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(p_taraliSec)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(p_doluSec, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(p_bosSec, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p_bosSec, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_doluSec, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_taraliSec, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(12, 12, 12)
                            .addComponent(i_cizgiSec, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(o_cizgiSec, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(k_cizgiSec, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(k_noktaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(o_noktaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b_noktaSec, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(135, 250, 248));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Çizim Alanı Boyutu"));
        jPanel4.setForeground(new java.awt.Color(35, 8, 141));

        jLabel3.setText("X (0-1200):");

        jLabel5.setText("Y(0-500):");

        olusturButon.setText("Oluştur");
        olusturButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olusturButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xBoyutu)
                    .addComponent(yBoyutu)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(olusturButon, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(xBoyutu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yBoyutu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(olusturButon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(135, 250, 248));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Koordinat"));
        jPanel5.setForeground(new java.awt.Color(35, 8, 141));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setText("(maksimum X veya Y- 30 arasında girin):");

        jButton1.setText("Çiz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("X:");

        jLabel9.setText("Y:");

        ekle1.setText("Ekle");
        ekle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle1ActionPerformed(evt);
            }
        });

        ekle2.setText("Ekle");
        ekle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle2ActionPerformed(evt);
            }
        });

        temizle.setText("Temizle");
        temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(xKoordinat, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(yKoordinat))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ekle1)
                                    .addComponent(ekle2))))
                        .addGap(14, 14, 14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(14, 14, 14)
                        .addComponent(temizle)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ekle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xKoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yKoordinat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(ekle2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temizle, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void o_cizgiSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_o_cizgiSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_o_cizgiSecActionPerformed

    private void olusturButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olusturButonActionPerformed
        //x verisi alan kısım
        setCizimAlaniX(Integer.parseInt(xBoyutu.getText()));
        setCizimAlaniy(Integer.parseInt(yBoyutu.getText()));

        if (getCizimAlaniX() < 0) {
            JOptionPane.showMessageDialog(null, "0'dan küçük değer girilemez !");
            setCizimAlaniy(0);
        } else if (getCizimAlaniX() > 1200) {
            JOptionPane.showMessageDialog(null, "1200'den büyük değer girilemez !");
            setCizimAlaniy(1200);
        }

        //y verisi alan kısım
        if (getCizimAlaniy() < 0) {
            JOptionPane.showMessageDialog(null, "0'dan küçük değer girilemez !");
            setCizimAlaniy(0);
        } else if (getCizimAlaniy() > 500) {
            JOptionPane.showMessageDialog(null, "500'den büyük değer girilemez !");
            setCizimAlaniy(500);
        }

        jPanel1.setBounds(70, 230, getCizimAlaniX(), getCizimAlaniy());


    }//GEN-LAST:event_olusturButonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sekil = (Graphics2D) jPanel1.getGraphics();

        if (nokta.isSelected()) {
            if (k_noktaSec.isSelected()) {
                sekil.fillOval(xK.get(0), yK.get(0), getKucukNoktaX(), getKucukNoktaY());
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");
            } else if (o_noktaSec.isSelected()) {
                sekil.fillOval(xK.get(0), yK.get(0), getOrtaNoktaX(), getOrtaNoktaY());
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");
            } else if (b_noktaSec.isSelected()) {
                sekil.fillOval(xK.get(0), yK.get(0), getBuyukNoktaX(), getBuyukNoktaY());
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");
            }

        } else if (cizgi.isSelected()) {

            if (i_cizgiSec.isSelected()) {
                sekil.setStroke(new BasicStroke(1));
                sekil.drawLine(xK.get(0), yK.get(0), xK.get(1), yK.get(1));
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");

            } else if (o_cizgiSec.isSelected()) {
                sekil.setStroke(new BasicStroke(3));
                sekil.drawLine(xK.get(0), yK.get(0), xK.get(1), yK.get(1));
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");

            } else if (k_cizgiSec.isSelected()) {
                sekil.setStroke(new BasicStroke(6));
                sekil.drawLine(xK.get(0), yK.get(0), xK.get(1), yK.get(1));
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");
            }

        } else if (poligon.isSelected()) {
            int[] arrX = new int[xK.size()];

            for (int i = 0; i < xK.size(); i++) {
                if (xK.get(i) != null) {
                    arrX[i] = xK.get(i);
                }
            }
            int[] arrY = new int[yK.size()];

            for (int i = 0; i < yK.size(); i++) {
                if (yK.get(i) != null) {
                    arrY[i] = yK.get(i);
                }
            }

            if (p_bosSec.isSelected()) {
                sekil.drawPolygon(arrX, arrY, getPoligonNoktaSayisi());
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");

            } else if (p_doluSec.isSelected()) {

                sekil.fillPolygon(arrX, arrY, getPoligonNoktaSayisi());
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");

            } else if (p_taraliSec.isSelected()) {
               
                
                sekil.fillPolygon(arrX, arrY, getPoligonNoktaSayisi());
                
                xK.clear();
                yK.clear();
                JOptionPane.showMessageDialog(null, "yeni koordinatları giriniz.");

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ekle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle1ActionPerformed
        if (nokta.isSelected()) { //1 adet x noktası eklemek için

            if (Integer.parseInt(xKoordinat.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "0'dan küçük değer girilemez !");
            } else if (Integer.parseInt(xKoordinat.getText()) > getCizimAlaniX() - 30) {
                JOptionPane.showMessageDialog(null, getCizimAlaniX() - 30 + "dan büyük değer girilemez !");
            } else {
                xK.add(0, Integer.parseInt(xKoordinat.getText()));
            }
             if(xK.size() == 1){
                 JOptionPane.showMessageDialog(null, "Tüm X noktaları girildi.");   
                }
        } else if (cizgi.isSelected()) {

            if (Integer.parseInt(xKoordinat.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "0'dan küçük değer girilemez !");
            } else if (Integer.parseInt(xKoordinat.getText()) > getCizimAlaniX() - 30) {
                JOptionPane.showMessageDialog(null, getCizimAlaniX() - 30 + "dan büyük değer girilemez !");
            } else {
                xK.add(Integer.parseInt(xKoordinat.getText()));
                if (xK.size() > 2) {
                    JOptionPane.showMessageDialog(null, "3 nokta girildi x değerleri sıfırlanıyor");
                    xK.clear();
                }
                else if(xK.size() == 2){
                 JOptionPane.showMessageDialog(null, "Tüm X noktaları girildi.");   
                }

            }

        } else if (poligon.isSelected()) {
            if (Integer.parseInt(xKoordinat.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "0'dan küçük değer girilemez !");
            } else if (Integer.parseInt(xKoordinat.getText()) > getCizimAlaniX() - 30) {
                JOptionPane.showMessageDialog(null, getCizimAlaniX() - 30 + "dan büyük değer girilemez !");
            } else {
                xK.add(Integer.parseInt(xKoordinat.getText()));
                if (xK.size() > getPoligonNoktaSayisi()) {
                    JOptionPane.showMessageDialog(null, xK.size() + "nokta girildi x değerleri sıfırlanıyor");
                    xK.clear();

                }
                else if(xK.size() == getPoligonNoktaSayisi()){
                 JOptionPane.showMessageDialog(null, "Tüm X noktaları girildi.");   
                }
                
            }
        }


    }//GEN-LAST:event_ekle1ActionPerformed

    private void ekle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle2ActionPerformed
        if (nokta.isSelected()) { //1 adet y noktası eklemek için
            if (Integer.parseInt(yKoordinat.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "0'dan küçük değer girilemez !");
            } else if (Integer.parseInt(yKoordinat.getText()) > getCizimAlaniy() - 30) {
                JOptionPane.showMessageDialog(null, getCizimAlaniy() - 30 + "dan büyük değer girilemez !");
            } else {
                yK.add(0, Integer.parseInt(yKoordinat.getText()));
            }
            if(yK.size() == 1){
                 JOptionPane.showMessageDialog(null, "Tüm Y noktaları girildi.");   
                }
        } else if (cizgi.isSelected()) {
            if (Integer.parseInt(yKoordinat.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "0'dan küçük değer girilemez !");
            } else if (Integer.parseInt(yKoordinat.getText()) > getCizimAlaniy() - 30) {
                JOptionPane.showMessageDialog(null, getCizimAlaniy() - 30 + "dan büyük değer girilemez !");
            } else {
                yK.add(Integer.parseInt(yKoordinat.getText()));
                if (yK.size() > 2) {
                    JOptionPane.showMessageDialog(null, "3 nokta girildi y noktaları sıfırlanıyor.");
                    yK.clear();
                }
                else if(yK.size() == 2){
                 JOptionPane.showMessageDialog(null, "Tüm Y noktaları girildi.");   
                }
            }

        } else if (poligon.isSelected()) {
            if (Integer.parseInt(yKoordinat.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "0'dan küçük değer girilemez !");
            } else if (Integer.parseInt(yKoordinat.getText()) > getCizimAlaniy() - 30) {
                JOptionPane.showMessageDialog(null, getCizimAlaniy() - 30 + "dan büyük değer girilemez !");
            } else {
                yK.add(Integer.parseInt(yKoordinat.getText()));
                if (yK.size() > getPoligonNoktaSayisi()) {
                    JOptionPane.showMessageDialog(null, yK.size() + "nokta girildi y değerleri sıfırlanıyor");
                    yK.clear();

                }
                else if(yK.size() == getPoligonNoktaSayisi()){
                 JOptionPane.showMessageDialog(null, "Tüm Y noktaları girildi.");   
                }
            }

        }
    }//GEN-LAST:event_ekle2ActionPerformed

    private void temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleActionPerformed

        xK.clear();
        yK.clear();
        repaint();


    }//GEN-LAST:event_temizleActionPerformed

    private void cizgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cizgiActionPerformed
        JOptionPane.showMessageDialog(null, "Çizgi için önce x0,y0 ekleyin daha sonra x1,y1 ekleyin.");

    }//GEN-LAST:event_cizgiActionPerformed

    private void noktaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noktaActionPerformed
        JOptionPane.showMessageDialog(null, "Nokta için sadece x0,y0 ekleyin.");
    }//GEN-LAST:event_noktaActionPerformed

    private void poligonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poligonActionPerformed
        String sayi = JOptionPane.showInputDialog("Poligonun kaç noktalı olacağını giriniz.", null);
        setPoligonNoktaSayisi(Integer.parseInt(sayi));
        JOptionPane.showMessageDialog(null, "Poligon için "+ getPoligonNoktaSayisi() +" adet x ve y noktası ekleyin.");


    }//GEN-LAST:event_poligonActionPerformed

    private void p_taraliSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_taraliSecActionPerformed
       JOptionPane.showMessageDialog(null, "İçi taralı poligonu oluşturamadım.");
    }//GEN-LAST:event_p_taraliSecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pencere.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pencere().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton b_noktaSec;
    private javax.swing.JRadioButton cizgi;
    private javax.swing.ButtonGroup cizgiGrup;
    private javax.swing.JButton ekle1;
    private javax.swing.JButton ekle2;
    private javax.swing.JRadioButton i_cizgiSec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton k_cizgiSec;
    private javax.swing.JRadioButton k_noktaSec;
    private javax.swing.JLabel labelCizgi;
    private javax.swing.JLabel labelNokta;
    private javax.swing.JLabel labelPoligon;
    private javax.swing.JRadioButton nokta;
    private javax.swing.ButtonGroup noktaGrup;
    private javax.swing.JRadioButton o_cizgiSec;
    private javax.swing.JRadioButton o_noktaSec;
    private javax.swing.JButton olusturButon;
    private javax.swing.JRadioButton p_bosSec;
    private javax.swing.JRadioButton p_doluSec;
    private javax.swing.JRadioButton p_taraliSec;
    private javax.swing.JRadioButton poligon;
    private javax.swing.ButtonGroup poligonGrup;
    private javax.swing.ButtonGroup secenekGrup;
    private javax.swing.JButton temizle;
    private javax.swing.JTextField xBoyutu;
    private javax.swing.JTextField xKoordinat;
    private javax.swing.JTextField yBoyutu;
    private javax.swing.JTextField yKoordinat;
    // End of variables declaration//GEN-END:variables
}
